function [coeff, fitresult, gof] = getPowerCoeff(currentSF, currentPS)
%CREATEFIT(CURRENTSF,CURRENTPS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : currentSF
%      Y Output: currentPS
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Feb-2017 16:34:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( currentSF, currentPS );

% Set up fittype and options.
ft = fittype( '(-a*x+b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Robust = 'Bisquare';
opts.StartPoint = [0.722905352239109 0.811753323578174];


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

coeff = fitresult.a;
% 
% % Plot fit with data.
% figure(99);hold on;
% h = plot( fitresult, xData, yData );
% legend( h, 'currentPS vs. currentSF', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel currentSF
% ylabel currentPS
% grid on
% set(gca,'XScale','log')
% set(gca,'YScale','log')


